### PR TITLE
Update instructions for chart release and installation.

### LINKED ISSUE #701: Provide a versioned helm chart with each release
- [x] Update [release doc](https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/releasing.md) to reflect the need to:
     - Create an archive of the helm chart that defaults to the released image tag
     - Create an sha hash of the chart archive
     - Include the archive and sha hash as release artifacts
     - Create a PR that updates the repo index of the chart to point to the location of the released chart
 - [x] Update the [helm install instructions](https://github.com/kubernetes-sigs/federation-v2/blob/master/charts/federation-v2/README.md) 
     - Explain how to add the federation chart repo (i.e. url to the repo index)
     - Explain how to install a specific version of the chart

/kind feature

cc: @sfxworks

### PR DESCRIPTION
**Pull request by marun**
We have a released chart but no instructions on how to use it.   This needs to merge ASAP.

Supersedes #751 
Fixes #701

### CODE REVIEW

**Comment by marun** [comment]
I'm waiting on @sfxworks to sign the CLA for the email he authored the commit with.

**Comment by sfxworks** [comment]
Sorry for the delay! Added services@ to my github account.

**Comment by xunpan** [comment]
LGTM

**Comment by shashidharatd** [comment]
/lgtm
Thanks @sfxworks @marun !

**Pull request merged**
