### PR TITLE
support multiple namespaced federation with helm

### LINKED ISSUE #557: Install multiple namespaced fedeartion is failed
**What happened**:
1. When second namespaced federation is deployed by deployment script. The operation is failed.

```
$ FEDERATION_NAMESPACE=foo NAMESPACED=y ./scripts/deploy-federation.sh happur/fedv2:test cluster2
...
$ # done successfully

$ FEDERATION_NAMESPACE=dup NAMESPACED=y ./scripts/deploy-federation.sh happur/fedv2:test cluster2
...
F0122 22:15:08.855409    2580 enable.go:117] error: Error creating CRD "federatedclusterroles.primitives.federation.k8s.io": customresourcedefinitions.apiextensions.k8s.io "federatedclusterroles.primitives.federation.k8s.io" already exists
```

2. When skip federate step in the script and manually join cluster. It still failed in
```
I0123 01:25:33.795001    5923 join.go:630] Could not create health check cluster role for service account: cluster2-cluster1 in joining cluster: cluster2 due to: clusterroles.rbac.authorization.k8s.io "federation-controller-manager:healthcheck-cluster2-cluster1" already exists
```
The reason is that our health check uses cluster role.

**What you expected to happen**:
Namespaced federation shold deployed for multiple instances.

**How to reproduce it (as minimally and precisely as possible)**:
see above

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`)
- Federation version
- Install method (helm vs script)
both of them have this issue

- Install configuration (namespaced vs cluster-scoped)
namespaced

- Others

/kind bug

### PR DESCRIPTION
**Pull request by xunpan**
- checking CRDs to see if it exists by group api in helm chart
 - helm installation script to support multiple namespaced federation

After this merged, #628, #629, #630 should be merged. Then

Fixes #557

### CODE REVIEW

**Comment by xunpan** [comment]
rebase done and CI passed. @marun

**Comment by marun** [comment]
@xunpan This looks ok to me, though I'm no helm expert.  

What do you think of removing federated type configs/federated type crds from the helm chart once `kubefed2 federate` extends support to federating namespaces?  cc: @irfanurrehman 

@gyliu513 Can you please review?

**Comment by gyliu513** [comment]
I have talked this @xunpan offline for this PR, and it looks good to me.

@marun @xunpan if we want to remove federated type configs/federated type crds from the helm chart, we may want to resume https://github.com/kubernetes-sigs/federation-v2/pull/482 by enabling some pre/post script in helm chart to manage the federated crds.

/lgtm

**Comment by marun** [comment]
Thank you!

/approve

**Pull request merged**
