### PR TITLE
feat: make num workers configurable in dnsendpoint

### PR DESCRIPTION
**Pull request by draveness**

### CODE REVIEW

**Comment by marun** [comment]
What motivated you to make this change? It's effectively non-functional - no change in behavior or capability.

**Comment by draveness** [comment]
> What motivated you to make this change? It's effectively non-functional - no change in behavior or capability.

I found a TODO listed in the code - consider making numWorkers configurable. Do you have any suggestions on this?

**Comment by marun** [comment]
@draveness I'm afraid you misread the import of the TODO, and I think you're unlikely to find productive work from the code alone.  At the least I suggest engaging with the author of the TODO.  Also, we file issues for things that we identify as priorities - TODOs are mere bookmarks to consider in future maintenance that touches the code.

Please reach out to me on #sig-multicluster on kube slack so that I may assist you in your search for meaningful contribution.

**Pull request closed without merging**
