### PR TITLE
Doc kubefedctl federate

### PR DESCRIPTION
**Pull request by xunpan**
It is valuable to be documented for users

### CODE REVIEW

**Comment by marun** [comment]
@irfanurrehman I'm confused, did you delegate this to @xunpan or does this PR represent a duplication of your in-progress efforts?

**Comment by marun** [comment]
@xunpan Unless I'm mistaken this was work that @irfanurrehman was committed to completing as part of #477.  Did you discuss with him before taking it on?

**Comment by irfanurrehman** [comment]
No I did not delegate it. @xunpan did I give you an indication that I m not working on this... :-)

Infact I gave my status in today's standup also indicating that I should be able to publish a PR on this by tomorrow..

**Comment by marun** [comment]
@xunpan Please close this, and in future, please make sure to coordinate with the owner of a feature (if one exists) to avoid duplicating effort.

**Comment by xunpan** [comment]
I did this because I found there is no doc for this part when I'm writing e2e case scripts.
If it is already part of another tickets, I'm fine with it.

**Pull request closed without merging**
