### PR TITLE
Skip Travis build for doc-only changes

### LINKED ISSUE #575: Skip Travis build for doc-only changes
The Travis CI build is triggered regardless of changes made in the PR, Which is not a desirable outcome in case of doc-only changes.

There is an open Issue in travis CI (https://github.com/travis-ci/travis-ci/issues/6301) for the same, but as it's not being followed up, other repos have implemented it on their side.

Ref:
https://github.com/facebook/react/issues/1768
https://github.com/serverless/serverless/issues/2699

### PR DESCRIPTION
**Pull request by poothia**
closes #575

### CODE REVIEW

**Comment by marun** [comment]
Would it make more sense to look for changes in the doc directory to ensure non-md changes are captured (e.g. images)?

**Comment by poothia** [comment]
@marun agreed... i'll add the filter accordingly. thanks for pointing that out.

**Comment by poothia** [comment]
@marun updated, PTAL.

**Comment by marun** [comment]
/lgtm
/approve

Thank you!

**Pull request merged**
