### PR TITLE
code clean: fix some golint failures

### PR DESCRIPTION
**Pull request by SataQiu**
code clean: fix some golint failures

### CODE REVIEW

**Comment by marun** [comment]
@SataQiu What is the value of this kind of change if this repo is not enforcing it mechanically with golint in CI?

**Comment by marun** [comment]
@SataQiu I apologize if I gave the impression.  I wasn't asking for this PR to be closed.  I am open to the possibility of golint being added to our CI regime if a good case can be made for doing so.

**Comment by SataQiu** [comment]
Thanks @marun 
I just found some code in the project that didn't meet the requirements of `golint`, and tried to fix it, even though there was no CI constraint. If that doesn't make a lot of sense, I will contribute from other aspects.

**Comment by marun** [comment]
@SataQiu I can guess that ensuring golint compatibility would be a considerable task.

Feel free to reach out to me on #sig-multicluster on kubernetes.slack.com if you'd appreciate assistance in getting started with participating in the project.

**Comment by SataQiu** [comment]
@marun Thank you. I am happy to contribute and I will try my best!

**Pull request closed without merging**
