### PR TITLE
docs: Fix broken links and typos

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by yamt** [comment]
I signed it

**Comment by xunpan** [comment]
/lgtm
@gyliu513 

The CI failed case is not related to this fix.
/retest

**Comment by marun** [comment]
Please force-push a new change (e.g. by doing a no-op amend to the commit message) to get prow working again.

**Comment by gyliu513** [comment]
@marun can you show some detail for how to fix prow to ignore the `needs-ok-test` label?

**Comment by marun** [comment]
@gyliu513 There's no way to ignore it if prow won't merge with that label (and I can't confirm that this is required until prow starts merging again).  From a recent conversation with infra it doesn't sound like they want prow to behave differently.

**Pull request merged**
