### PR TITLE
Disable gofmt check until it can be made reliable

### PR DESCRIPTION
**Pull request by marun**
cc: @poothia

### CODE REVIEW

**Comment by poothia** [comment]
@marun i think we should revert this... ref: https://github.com/kubernetes-sigs/federation-v2/pull/390#issuecomment-436140394
thoughts??

**Comment by marun** [comment]
@poothia I'm open to re-enabling the gofmt check.

**Comment by poothia** [comment]
@marun ok, i'll open a PR to re-enable it... and fix any changes done, that might have not been gofmt compliant, but we need to get it merged before some other non-gofmt changes leak into master, and start breaking the CI again.

**Pull request merged**
