### PR TITLE
WIP Move federation-v2 from kubernetes-sigs to sigs.k8s.io under GOPATH

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed https://github.com/kubernetes-sigs/federation-v2/issues/697

### CODE REVIEW

**Comment by marun** [comment]
@gyliu513 I'll hold off on reviewing till CI is passing and you're removed WIP.

**Comment by gyliu513** [comment]
Will try to continue the work after https://github.com/kubernetes-sigs/federation-v2/pull/716 got merged.

**Comment by shashidharatd** [comment]
@gyliu513, please rebase

**Comment by marun** [comment]
@gyliu513 I think this work should be paused pending the outcome of the proposed repo rename to `kubefed`.

**Comment by shashidharatd** [comment]
Closing this pr as this is superseded by https://github.com/kubernetes-sigs/federation-v2/pull/865

**Pull request closed without merging**
