### PR TITLE
Sync up federation YAML templates for helm chart

### PR DESCRIPTION
**Pull request by gyliu513**
/cc @marun

### CODE REVIEW

**Comment by gyliu513** [comment]
@marun any comments for why the CI failed? I was using a fed v2 image built by myself to generate all of the YAML templates, but the CI fed v2 image seems generating some different YAML templates at https://travis-ci.org/kubernetes-sigs/federation-v2/builds/463723545?utm_source=github_status&utm_medium=notification , any comments?

```
diff --git a/charts/federation-v2/templates/deployments.apps.yaml b/charts/federation-v2/templates/deployments.apps.yaml
index 92d9d017..5579f6e1 100644
--- a/charts/federation-v2/templates/deployments.apps.yaml
+++ b/charts/federation-v2/templates/deployments.apps.yaml
@@ -1010,6 +1010,8 @@ spec:
                                         type: object
                                       privileged:
                                         type: boolean
+                                      procMount:
+                                        type: string
                                       readOnlyRootFilesystem:
                                         type: boolean
                                       runAsGroup:
@@ -1500,6 +1502,8 @@ spec:
                                         type: object
                                       privileged:
                                         type: boolean
+                                      procMount:
+                                        type: string
                                       readOnlyRootFilesystem:
                                         type: boolean
                                       runAsGroup:
@@ -1590,6 +1594,8 @@ spec:
                               type: array
                             restartPolicy:
                               type: string
+                            runtimeClassName:
+                              type: string
                             schedulerName:
                               type: string
                             securityContext:
diff --git a/charts/federation-v2/templates/jobs.batch.yaml b/charts/federation-v2/templates/jobs.batch.yaml
index 691649b7..aa42fb45 100644
--- a/charts/federation-v2/templates/jobs.batch.yaml
+++ b/charts/federation-v2/templates/jobs.batch.yaml
@@ -992,6 +992,8 @@ spec:
                                         type: object
                                       privileged:
                                         type: boolean
+                                      procMount:
+                                        type: string
                                       readOnlyRootFilesystem:
                                         type: boolean
                                       runAsGroup:
@@ -1482,6 +1484,8 @@ spec:
                                         type: object
                                       privileged:
                                         type: boolean
+                                      procMount:
+                                        type: string
                                       readOnlyRootFilesystem:
                                         type: boolean
                                       runAsGroup:
@@ -1572,6 +1576,8 @@ spec:
                               type: array
                             restartPolicy:
                               type: string
+                            runtimeClassName:
+                              type: string
                             schedulerName:
                               type: string
                             securityContext:
@@ -2206,6 +2212,9 @@ spec:
                           - containers
                           type: object
                       type: object
+                    ttlSecondsAfterFinished:
+                      format: int32
+                      type: integer
                   required:
                   - template
                   type: object
diff --git a/charts/federation-v2/templates/replicasets.apps.yaml b/charts/federation-v2/templates/replicasets.apps.yaml
index 7fe90e0b..c06c40ee 100644
--- a/charts/federation-v2/templates/replicasets.apps.yaml
+++ b/charts/federation-v2/templates/replicasets.apps.yaml
@@ -984,6 +984,8 @@ spec:
                                         type: object
                                       privileged:
                                         type: boolean
+                                      procMount:
+                                        type: string
                                       readOnlyRootFilesystem:
                                         type: boolean
                                       runAsGroup:
@@ -1474,6 +1476,8 @@ spec:
                                         type: object
                                       privileged:
                                         type: boolean
+                                      procMount:
+                                        type: string
                                       readOnlyRootFilesystem:
                                         type: boolean
                                       runAsGroup:
@@ -1564,6 +1568,8 @@ spec:
                               type: array
                             restartPolicy:
                               type: string
+                            runtimeClassName:
+                              type: string
                             schedulerName:
                               type: string
                             securityContext:
```

**Comment by marun** [comment]
@gyliu513 The crd validation schema is generated from openapi schema retrieved from the default kube apiserver configured where `kubefed2` is invoked.  The CI failure is likely the result of a difference between the version of kube used in ci and the version of kube in your local environment, which suggests the need to commit the kube version to the tree in some form.

cc: @font

**Comment by gyliu513** [comment]
@marun chart is synced now.

**Comment by marun** [comment]
@gyliu513 My point is that updating the generated crds for helm will require that a developer use the same version of kubernetes that CI is intended to use.  It doesn't matter what version a developer is using if they are not updating the chart, and I expect the generated crds to change very infrequently once we reach beta and beyond.

**Comment by gyliu513** [comment]
+1 for this, thanks @marun . Any comments for the current PR, can this get merged?

**Comment by marun** [comment]
Wow, I just noticed how big some of the crds are with validation.  

/approve
/lgtm

**Pull request merged**
