### PR TITLE
Add feature gates

### PR DESCRIPTION
**Pull request by shashidharatd**
Ref: #101 
here is an first cut attempt to implement feature-gates to control which features(controllers as of now) should be enabled. Is this what is desired?

/cc @marun @pmorie @irfanurrehman

### CODE REVIEW

**Comment by marun** [comment]
I'm not familiar with this approach, does kube use it?  I was expecting something more like `--schedule-deployments=true|false` and `--push-reconciler=true|false`.  That said, if @pmorie wants this and you're happy with it, I think it's fine.

**Comment by shashidharatd** [comment]
@marun, it is more or less similar to what you are expecting. instead of multiple individual flags for each feature it would be something like `--feature-gates=SchedulerPreferences=true,PushReconciler=true`

**Comment by marun** [comment]
@shashidharatd I think that looks more like a way to enable/disable a feature in CI than something I would want to expose to a user.  For alpha, though, it's probably fine.

**Comment by pmorie** [comment]
@marun the feature gate mechanism is used by k8s. We can configure parameters of features with CLI options, enable/disable with feature gates.

**Comment by pmorie** [comment]
Thanks a lot for this @shashidharatd !

/lgtm

**Pull request merged**
