### PR TITLE
Document how to determine that a target type is present in all federated clusters

### LINKED ISSUE #827: Document how to determine that a target type is present in all federated clusters
This is intended to document how to manually do what #314 is intended to automate.

### PR DESCRIPTION
**Pull request by font**
Fixes #827

### CODE REVIEW

**Comment by marun** [comment]
@font As per the title of this PR (and associated issue), the requirement is to document how to detect whether a target type is present in all member clusters.  The proposed documentation works for CRDs, but a target type could also be a core type that had been disabled or a non-core type that had been added via aggregation.  Is it desirable to have separate paths for crds vs core and aggregated types, or would the following be workable?

```
kubectl api-resources | grep <group> | grep <kind or plural name>
```

**Comment by font** [comment]
@marun While CRDs may be the main issue, you're right it's incomplete. I've updated. Thanks!

**Comment by marun** [comment]
LGTM

**Pull request merged**
