### PR TITLE
Update the comment of the function

### PR DESCRIPTION
**Pull request by xichengliudui**
Update the comment of the function

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
@xichengliudui can you also update the command mentioned here:
https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/federating_crds.md#enable-propagation-of-your-federated-crd
you just need to append apply command before -f option.
```sh
$ kubectl *apply* -f ./example/crd/federatedBar.yaml --context=cluster1
federatedtypeconfig.core.federation.k8s.io/bars.example.io created
```

**Comment by pmorie** [comment]
> @xichengliudui can you also update the command mentioned here:

Let's not expand the scope of this PR, @sohankunkerkar would you go ahead and just fix that in a PR since you know that it's an issue?

**Pull request merged**
