### PR TITLE
make log level lower to consist with reconcile message 

### PR DESCRIPTION
**Pull request by xunpan**
This message is not necessary. It makes log message not readable because lots of them printed quickly.

Refer to https://github.com/kubernetes-sigs/federation-v2/pull/617#discussion_r261435218 for information

### CODE REVIEW

**Comment by marun** [comment]
I think you've got the right idea here - this message doesn't have to appear repeatedly.  How often will it be logged (regardless of level)?

**Comment by xunpan** [comment]
2 messages is logged repeatly every 2 seconds in my environment.
```
I0306 05:58:00.515905       1 controller.go:163] Skipping start of sync & status controller for cluster-scoped resource "Fede│I0306 05:57:12.933206       1 controller.go:134] Shutting down "ingress" DNSEndpoint controller
ratedClusterRole".  It is not required for a namespaced federation control plane.                                            │I0306 05:57:12.933605       1 controller.go:134] Shutting down "service" DNSEndpoint controller
I0306 05:58:00.812859       1 controller.go:163] Skipping start of sync & status controller for cluster-scoped resource "Fede│rpc error: code = Unknown desc = Error: No such container: 5a62176bf72013f3d513bf8ffca53c36d0602f0e9436f
ratedNamespace".  It is not required for a namespaced federation control plane.                                              │8a6568bd0142e717ec1panpxpx@lsftest01:~$ kubectl get crd
I0306 05:58:02.510431       1 controller.go:163] Skipping start of sync & status controller for cluster-scoped resource "Fede│NAME                                                        CREATED AT
ratedClusterRole".  It is not required for a namespaced federation control plane.                                            │clusterpropagatedversions.core.federation.k8s.io            2019-03-06T05:56:03Z
I0306 05:58:02.714683       1 controller.go:163] Skipping start of sync & status controller for cluster-scoped resource "Fede│dnsendpoints.multiclusterdns.federation.k8s.io              2019-03-06T05:56:03Z
ratedNamespace".  It is not required for a namespaced federation control plane.  
...
```

**Comment by marun** [comment]
@xunpan I think that suggests logging the message only once per type rather than decreasing the log level.

**Comment by xunpan** [comment]
Resolved. The message only print once for each type.

**Comment by marun** [comment]
Nicely done, thank you!

/approve
/lgtm

**Pull request merged**
