### PR TITLE
Rename `Host` to `HostClusterContext` for `join`.

### PR DESCRIPTION
**Pull request by gyliu513**
Fixed https://github.com/kubernetes-sigs/federation-v2/issues/165

/cc @font @marun

### CODE REVIEW

**Comment by marun** [comment]
Ugh, seeing transient travis build failures due to running both e2e and integration.

@gyliu513 I'll allow this.  However, the code is alpha quality, intended to lay down enough functionality for users to provide substantive feedback.  I would like to avoid filing issues for every single corner we've cut in the process.  I would rather see trivial refactors and renames such as this one incorporated into more substantive work to minimize the overhead involved.

**Comment by gyliu513** [comment]
> I would rather see trivial refactors and renames such as this one incorporated into more substantive work to minimize the overhead involved.

@marun so you mean that we want to combine such fix when doing some other function level change?

**Comment by marun** [comment]
@gyliu513 Correct.  Much of the code quality has not been exhaustively reviewed and lacks comprehensive test coverage, in keeping with work whose primary purpose is to validate assumptions about user requirements.  As such, I think minor refactoring and stabilization efforts are of a lower priority to work driven by user requirements.

**Pull request merged**
