### PR TITLE
fix status controller not reconcile when federation has no readyCluster

### PR DESCRIPTION
**Pull request by braceinhz**
Issue:https://github.com/kubernetes-sigs/federation-v2/issues/677

### CODE REVIEW

**Comment by braceinhz** [comment]
@k8s-ci-robot /ok-to-test

**Comment by marun** [comment]
> @k8s-ci-robot /ok-to-test

That command does nothing in this repo, the bot assumes prow but we use travis.  If you look at the checks, CI has run and is passing.

**Comment by marun** [comment]
@shashidharatd Would you be able to review this?

**Comment by shashidharatd** [comment]
@braceinhz, apologies for the delay in review. Thanks for the fix !
/lgtm
/approve

**Pull request merged**
