### PR TITLE
Enable sequenced cluster naming in test setup

### PR DESCRIPTION
**Pull request by irfanurrehman**
As the title suggests. This is needed in tests for scheduling preferences, where preferences are specified against the cluster names.

### CODE REVIEW

**Comment by irfanurrehman** [comment]
This was raised to be useful for tests in https://github.com/kubernetes-sigs/federation-v2/pull/46 and any other similar controller.
@maru @font @pmorie @shashidharatd PTAL.

**Comment by irfanurrehman** [comment]
@maru @font @pmorie, I would ideally want atleast one of you to have a look and/or ok this, as this effects the common test code.

**Comment by marun** [comment]
Hard-coding cluster naming for testing is an anti-pattern, and will complicate reuse of tests across managed and unamanged test fixture.  Please revise the test additions for #46 to use the names of member clusters such that this PR is no longer necessary.

**Comment by irfanurrehman** [comment]
Acknowledge, and closing this one. Additionally updated the tests in #46.
/close

**Pull request closed without merging**
