### PR TITLE
Adds region/zone level custom naming support for ServiceDNSRecords

### PR DESCRIPTION
**Pull request by danehans**
Setting `dnsPrefix` for a `ServiceDNSRecord` causes zone/region level records to use the service name instead of `dnsPrefix`. This is by design. However, use cases exist for DNS name customization at global, region, and zone scopes. This PR introduces the `ExternalName` field to the `ServiceDNSRecordSpec` type to provide this functionality while keeping `dnsPrefix` as-is.

Fixes https://github.com/kubernetes-sigs/federation-v2/issues/329

/cc @shashidharatd

### CODE REVIEW

**Comment by shashidharatd** [comment]
@danehans, There is slight misunderstanding here. According to the `dnsPrefix` field definition [here](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/apis/multiclusterdns/v1alpha1/servicednsrecord_types.go#L30), whenever it is specified an additional CNAME record is written with the name `<DNSPrefix>.<FederationDomain>` targetting global dns name for the service. Notice that there is no `namespace`, `federation` or keyword `svc` in the name. This is in-order to simplify the dns names for service and external clients could easily identify the federated service. (The name conflicts if any should be taken care by user themselves).

Now if you need such a simplified alternative DNS names at region and zone level. we could create additional CNAME records 
`<DNSPrefix>.<Region>.<FederationDomain>` --> region level DNS name
`<DNSPrefix>.<AvailabilityZone>.<Region>.<FederationDomain>` --> zone level DNS name

will this serve your purpose?

**Comment by danehans** [comment]
I believe that will serve my purpose. I’ll update the PR and resubmit.

**Comment by shashidharatd** [comment]
> I believe that will serve my purpose. I’ll update the PR and resubmit. However, can you help me understand the driver for still creating zone/region level resource records with the svc name instead of dnsPrefix when specified?

It is so because there need to be a mechanism for in-cluster DNS server to identify that the DNS query is a federation DNS query. The label preceding the `.svc` keyword is the federation name. Here is the code in CoreDNS on how it identifies the query is federation DNS query. https://github.com/coredns/coredns/blob/master/plugin/federation/federation.go#L130

**Comment by danehans** [comment]
@shashidharatd that makes sense. I still don't understand why we need to create the A and CNAME records when `dnsPrefix` is specified. Why not just substitute the `dnsPrefix` value for "svc" in the prefix? For example, here is the current naming scheme:

```
Global Level: svc-name.test-namespace.test-federation.svc.<federation-domain>
Region Level: svc-name.test-namespace.test-federation.svc.(status.DNS[*].region).<federation-domain>
Zone Level  : svc-name.test-namespace.test-federation.svc.(status.DNS[*].zone).(status.DNS[*].region).<federation-domain>
```

Here is the proposed scheme when `dnsPrefix` is specified:
```
Global Level: user-definied-prefix.test-namespace.test-federation.svc.<federation-domain>
Region Level: user-definied-prefix.test-namespace.test-federation.svc.(status.DNS[*].region).<federation-domain>
Zone Level  : user-definied-prefix.test-namespace.test-federation.svc.(status.DNS[*].zone).(status.DNS[*].region).<federation-domain>
```
We can use labels in the TXT records to specify the service name that is associated to the `dnsPrefix`. This will provide a traceable path from the resource record through the system.

**Comment by danehans** [comment]
@shashidharatd I just refactored the PR based on the approach of my previous comment. I performed a test Istio deploy and this is what the `DNSEndpoint` looks like with `dnsPrefix: bookinfo`:
```
$ kubectl get dnsendpoints -n istio-system -o yaml
apiVersion: v1
items:
- apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
  kind: DNSEndpoint
  metadata:
    creationTimestamp: 2018-11-26T18:21:07Z
    generation: 2
    name: service-istio-ingressgateway
    namespace: istio-system
    resourceVersion: "1090377"
    selfLink: /apis/multiclusterdns.federation.k8s.io/v1alpha1/namespaces/istio-system/dnsendpoints/service-istio-ingressgateway
    uid: 0b06bd19-f1a8-11e8-a811-42010a8a00af
  spec:
    endpoints:
    - dnsName: bookinfo.istio-system.external.svc.external.daneyon.com
      labels:
        serviceName: istio-ingressgateway
      recordTTL: 300
      recordType: A
      targets:
      - 35.197.25.218
      - 35.199.171.6
    - dnsName: bookinfo.istio-system.external.svc.us-west1-a.us-west1.external.daneyon.com
      labels:
        serviceName: istio-ingressgateway
      recordTTL: 300
      recordType: A
      targets:
      - 35.197.25.218
    - dnsName: bookinfo.istio-system.external.svc.us-west1-b.us-west1.external.daneyon.com
      labels:
        serviceName: istio-ingressgateway
      recordTTL: 300
      recordType: A
      targets:
      - 35.199.171.6
    - dnsName: bookinfo.istio-system.external.svc.us-west1.external.daneyon.com
      labels:
        serviceName: istio-ingressgateway
      recordTTL: 300
      recordType: A
      targets:
      - 35.197.25.218
      - 35.199.171.6
  status:
    observedGeneration: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

This is what the gcloud dns resource records look like:
```
$ gcloud dns record-sets list --zone="external-daneyon"
NAME                                                                               TYPE  TTL    DATA
external.daneyon.com.                                                              NS    21600  ns-cloud-c1.googledomains.com.,ns-cloud-c2.googledomains.com.,ns-cloud-c3.googledomains.com.,ns-cloud-c4.googledomains.com.
external.daneyon.com.                                                              SOA   21600  ns-cloud-c1.googledomains.com. cloud-dns-hostmaster.google.com. 1 21600 3600 259200 300
bookinfo.istio-system.external.svc.external.daneyon.com.                           A     300    35.197.25.218,35.199.171.6
cnamebookinfo.istio-system.external.svc.external.daneyon.com.                      TXT   300    "heritage=external-dns,external-dns/owner=change_me,external-dns/serviceName=istio-ingressgateway"
bookinfo.istio-system.external.svc.us-west1.external.daneyon.com.                  A     300    35.197.25.218,35.199.171.6
cnamebookinfo.istio-system.external.svc.us-west1.external.daneyon.com.             TXT   300    "heritage=external-dns,external-dns/owner=change_me,external-dns/serviceName=istio-ingressgateway"
bookinfo.istio-system.external.svc.us-west1-a.us-west1.external.daneyon.com.       A     300    35.197.25.218
cnamebookinfo.istio-system.external.svc.us-west1-a.us-west1.external.daneyon.com.  TXT   300    "heritage=external-dns,external-dns/owner=change_me,external-dns/serviceName=istio-ingressgateway"
bookinfo.istio-system.external.svc.us-west1-b.us-west1.external.daneyon.com.       A     300    35.199.171.6
cnamebookinfo.istio-system.external.svc.us-west1-b.us-west1.external.daneyon.com.  TXT   300    "heritage=external-dns,external-dns/owner=change_me,external-dns/serviceName=istio-ingressgateway"
```

From my standpoint, this approach creates less records, is easier for users to understand, and easier to understand the dnsendpoint<>svc association.

**Comment by shashidharatd** [comment]
@danehans, as we discussed over slack, the `dnsPrefix` field in current form is to provide additional vanity 
 URLs at global/region/zone level names for a federated service. So lets devise another field which would do what you wish to do in this pr.

**Comment by danehans** [comment]
OK. Here are suggestions for the name of the new field `ServiceNameOverride` or `HostnameOverride`. The definition for the field is:

`ServiceNameOverride`/`HostnameOverride` when specified, replaces the service name portion of DNS resource records of type `A` with `ServiceNameOverride`/`HostnameOverride`.

For example, given the following values:
```
spec.servicenameoverride/hostnameoverride: test-override
service.metadata.namespace: test-namespace
spec.federationName: test-federation
```

The following set of DNS names will be programmed:
```
Global Level: test-override.test-namespace.test-federation.svc.<federation-domain>
Region Level: test-override.test-namespace.test-federation.svc.(status.DNS[*].region).<federation-domain>
Zone Level: test-override.test-namespace.test-federation.svc.(status.DNS[*].zone).(status.DNS[*].region).<federation-domain>
```

**Comment by shashidharatd** [comment]
@danehans, your suggestion lgtm. please update the pr accordingly. thanks!

**Comment by shashidharatd** [comment]
@danehans, this LGTM. CI is failing, can you please check. Thanks !

**Comment by danehans** [comment]
@shashidharatd Thanks for the review. CI now passes.

**Pull request merged**
