### PR TITLE
Flush log immediately for controller manager.

### PR DESCRIPTION
**Pull request by gyliu513**
/cc @marun

### CODE REVIEW

**Comment by gyliu513** [comment]
There is no logs for controller manager now if we are using `glog`, how about put this in alpha as well?

/cc @marun @font @shashidharatd

**Comment by marun** [comment]
@gyliu513 This change doesn't enable logs - it just affects the flush interval.  I think it can wait until post-alpha.

**Comment by gyliu513** [comment]
@marun Yes, this is also the official way how Kubernetes handle its logs, hope we can have this post-alpha.

**Comment by gyliu513** [comment]
@marun I think we already released alpha, so can you help review this to check if this can be merged?

**Pull request merged**
