### PR TITLE
Rename repo to kubefed

### PR DESCRIPTION
**Pull request by shashidharatd**
Ref: https://github.com/kubernetes-sigs/federation-v2/issues/860

### CODE REVIEW

**Comment by marun** [comment]
How on earth is this passing CI in advance of the repo rename?

**Comment by marun** [comment]
Some additional TODOs.  This is by no means complete, and I intend to re-review as you post updates and add to this list as I find more items.

 - [ ] - `s/federation controllers/kubefed controllers/` (comments and docs)
 - [ ] - `s/federation-namespace/kubefed-namespace/` (controller manager and e2e arg)
 - [ ] - `s/federation namespace/kubefed namespace/` (comments and docs)
 - [ ] - `s/federation-config/kubefed-config/` (controller manager arg)
 - [ ] - `s/federationConfig/kubefedConfig/` (controller manager code)
 - [ ] - `s/federation config/kubefed config/` (controller manager comments)
 - [ ] - `s/FederationSystemNamespace/KubefedSystemNamespace/`
 - [ ] - `s/federationNamespace/kubefedNamespace/`
 - [ ] - `s/federation-controller-manager/kubefed-controller-manager/`
 - [ ] - `s/federation control plane/kubefed control plane/` (comments and docs)
 - [ ] - `s/FederationConfig/KubefedConfig/` (also need to rename example config files)
 - [ ] - `s/federation/kubefed/` (in docs and comments where appropriate.  'federation of a resource' is an appropriate use.  something like 'federation API' needs to be changed to 'kubefed API')
 - [ ] - `s/federation v2/kubefed/` (commands and docs)
 - [ ] - `s/federation/kubefed/` (names of roles, role bindings, service accounts, deployment name for helm chart and related documentation)
 - [ ] - `s/federation.k8s.io/kubefed.k8s.io/` group names for kubefed types (including generated types)

**Comment by marun** [comment]
Maybe it makes sense to do this work in 2 PRs - one that changes all public-facing references and a second to change the internal references?

**Comment by shashidharatd** [comment]
> How on earth is this passing CI in advance of the repo rename?

Because of this https://github.com/kubernetes-sigs/federation-v2/pull/865/files#diff-354f30a63fb0907d4ad57269548329e3R7

**Comment by pmorie** [comment]
> Maybe it makes sense to do this work in 2 PRs - one that changes all public-facing references and a second to change the internal references?

Agree - and I think we want to change the internal references first

**Comment by marun** [comment]
Please rebase on top of https://github.com/kubernetes-sigs/federation-v2/pull/843 - I'd really rather not have to rebase that monster.

**Comment by shashidharatd** [comment]
Rebased. Have tried to address all todo items except one. probably that one can be handled in a follow-up.

**Comment by marun** [comment]
I'll be reviewing this shortly, and intend to merge it ASAP if possible.

**Comment by shashidharatd** [comment]
@marun, @font, Found some mistakes, have corrected them now. request to review commit by commit. will try to add any changes further as separate commits until review is over.

**Comment by marun** [comment]
/lgtm

CI is passing, merging to get this ball rolling.  We can address fixes in subsequent PRs.

**Pull request merged**
