### PR TITLE
Changed apiVerison from core.federation.k8s.io/v1alpha1 to primitives.federation.k8s.io/v1alpha1

### PR DESCRIPTION
**Pull request by qinpingli**
Bug fix for issue #475

### CODE REVIEW

**Comment by gyliu513** [comment]
/ok-to-test

Thanks @qinpingli , please sign the CLA first.

**Comment by qinpingli** [comment]
@gyliu513 Done.

**Comment by gyliu513** [comment]
@qinpingli I applied your PR and run `kubectl apply -f example/sample1/`, then got the following error, can you please fix those two issues as well?

```
Error from server (Invalid): error when creating "example/sample1/federatedsecret-override.yaml": FederatedSecretOverride.primitives.federation.k8s.io "test-secret" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"primitives.federation.k8s.io/v1alpha1", "kind":"FederatedSecretOverride", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"primitives.federation.k8s.io/v1alpha1\",\"kind\":\"FederatedSecretOverride\",\"metadata\":{\"annotations\":{},\"name\":\"test-secret\",\"namespace\":\"test-namespace\"},\"spec\":{\"overrides\":[{\"clusterName\":\"cluster2\",\"data\":{\"A\":null}}]}}\n"}, "generation":1, "uid":"7595ca3e-f6e9-11e8-b984-00163e01fa8a", "selfLink":"", "clusterName":"", "name":"test-secret", "namespace":"test-namespace", "creationTimestamp":"2018-12-03T10:51:59Z"}, "spec":map[string]interface {}{"overrides":[]interface {}{map[string]interface {}{"clusterName":"cluster2", "data":map[string]interface {}{"A":interface {}(nil)}}}}}: validation failure list:
spec.overrides.data.A in body must be of type string: "null"
[unable to recognize "example/sample1/federatedclusterrolebinding-placement.yaml": no matches for kind "FederatedClusterRoleBindingPlacement" in version "primitives.federation.k8s.io/v1alpha1", unable to recognize "example/sample1/federatedclusterrolebinding-template.yaml": no matches for kind "FederatedClusterRoleBinding" in version "primitives.federation.k8s.io/v1alpha1"]
```

**Comment by marun** [comment]
@gyliu513 I don't think the issues you are seeing are relevant to this PR.  The recent doc changes have switched to processing the example placement and overrides before use, so they should not be expected to apply to a cluster without error in their committed form.

/approve
/lgtm

**Pull request merged**
