### PR TITLE
Fix join to use passed-in federation namespace instead of a constant

### PR DESCRIPTION
**Pull request by gyliu513**
/cc @marun

### CODE REVIEW

**Comment by marun** [comment]
This is a non-functional change, so no, it can wait.

**Comment by gyliu513** [comment]
@marun I think we already released alpha, so can you help review this to check if this can be merged?

**Comment by marun** [comment]
The name of this PR and the associated commit suggests your intent is at odds with your code.  Consider rephrasing it to something like 'Fix join to use passed-in federation namespace instead of a constant'.

**Comment by gyliu513** [comment]
@marun done

**Pull request merged**
