### PR TITLE
WIP Switch from glog to klog

### LINKED ISSUE #694: Use a forked version of glog in kubernetes
Use the permanent forked version of glog for kubernetes instead of glog.

ref:
https://github.com/kubernetes/kubernetes/issues/70264
https://github.com/kubernetes/klog/blob/master/README.md

/kind feature

### PR DESCRIPTION
**Pull request by poothia**
closes #694

### CODE REVIEW

**Comment by marun** [comment]
Did you intend to vendor klog?

I would prefer to see imports for klog aliased to glog rather than touching every single reference to glog:

```golang
glog "k8s.io/klog"
```

I also encourage you to lay the groundwork for your efforts going forward by discussing changes you want to make with owners and/or reviewers of this repo to ensure that your efforts are in line with their expectations.  Even maintainers need to do the legwork of consensus building or risk wasted effort.

**Comment by poothia** [comment]
@marun 

> Did you intend to vendor klog?
> 

yes, I indend to vendor and write a gate check for the same too, so that it doesn't creep in again.

> I would prefer to see imports for klog aliased to glog rather than touching every single reference to glog:
> 
> ```go
> glog "k8s.io/klog"
> ```
>
Ok, i'll change it accordingly. 

> I also encourage you to lay the groundwork for your efforts going forward by discussing changes you want to make with owners and/or reviewers of this repo to ensure that your efforts are in line with their expectations.
sure, i'll keep it in mind from now on.

thanks for reviewing this.

**Comment by shashidharatd** [comment]
@poothia, Are you stuck on something with this pr?

**Comment by marun** [comment]
Superceded by #857

**Pull request closed without merging**
