### PR TITLE
Update diagrams after API unification

### PR DESCRIPTION
**Pull request by pmorie**
And make some minor changes to README text

### CODE REVIEW

**Comment by marun** [comment]
Lgtm.  Will leave it to a non-rher to do the honors.

**Comment by xunpan** [comment]
good diagram. It LGTM.
One question: where is the link to docs/images/propagation.png from the doc? I think we need such kind of description and link.

**Comment by shashidharatd** [comment]
LGTM. Thanks @pmorie. You might have missed linking `docs/images/propagation.png`. is that the case?

**Comment by pmorie** [comment]
> LGTM. Thanks @pmorie. You might have missed linking docs/images/propagation.png. is that the case?

@shashidharatd yep, I'm just adding it for now. I'll make a small doc PR that contextualizes it as a follow up.

**Comment by shashidharatd** [comment]
/lgtm
Thanks @pmorie

**Pull request merged**
