### PR TITLE
Adds .idea to .gitignore

### PR DESCRIPTION
**Pull request by danehans**
Updates .gitignore to ignore Intellij IDE project settings
stored in a .idea directory.

### CODE REVIEW

**Comment by marun** [comment]
@danehans @onyiny-ang I would rather not accept ignore changes that are environment specific.   I think it's preferable for developers to configure local ignores:

```
Run git config --global core.excludesfile ~/.gitignore and add patterns to your ~/.gitignore. 
This option applies if you want to ignore certain patterns across all trees. 
I use this for .pyc and .pyo files, for example.
```
Source: https://stackoverflow.com/questions/1753070/how-do-i-configure-git-to-ignore-some-files-locally

**Comment by font** [comment]
I agree with @marun and were my thoughts exactly. We avoided the same thing in cluster registry for the same reasons.

**Comment by danehans** [comment]
@marun that worked for me. Thanks for the git pro tip :-)

You can close the issue if you would like.

**Comment by gyliu513** [comment]
You can also update `.git/info/exclude` to exclude specified files based on your environment.

**Pull request closed without merging**
